# See https://docs.docker.com/build/ci/github-actions/multi-platform/
name: Build and Push Image

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: read
  id-token: write

env:
  REGISTRY_IMAGE: grafana/kost
  # Docker image tags. See https://github.com/docker/metadata-action for format
  TAGS_CONFIG: |
    type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
    type=sha,prefix={{ branch }}-,format=short,enable=${{ github.ref == 'refs/heads/main' }}
    type=semver,pattern={{ version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        with:
          persist-credentials: false
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build and push
        uses: grafana/shared-workflows/actions/build-push-to-dockerhub@a30107276148b4f29eaeaef05a3f9173d1aa0ad9
        with:
          repository: ${{ env.REGISTRY_IMAGE }}
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.TAGS_CONFIG }}
